### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/view/ViewKt;

### ISSUE THREAD

**Issue by MahaleTushar** [Cuberto/liquid-swipe-android#7]
Getting runtime error of
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/view/ViewKt;

 at com.cuberto.liquid_swipe.LiquidPager.getBitmapAt(LiquidPager.kt:71)
        at com.cuberto.liquid_swipe.LiquidPager.getBitmap(LiquidPager.kt:66)
        at com.cuberto.liquid_swipe.animation.RightEdgeController.onPageChanged(RightEdgeController.kt:66)
        at com.cuberto.liquid_swipe.LiquidPager.onDraw(LiquidPager.kt:137)

**Comment by MahaleTushar** [comment]
the issue was caused becuase 
implementation 'androidx.core:core-ktx:1.2.0'

was missing
